### ISSUE TITLE
Enhance iceberg-go to Support Nessie API for All Catalog Operations

### ISSUE THREAD

**Issue by shubham-tomar** [apache/iceberg-go#291]
### Description

The current Catalog interface in iceberg-go is designed for the Iceberg REST catalog, but it does not fully align with Project Nessie’s API requirements. Nessie uses different API paths, request payloads, and reference (branch/tag) handling, which needs adjustments across all catalog operations. And it has different [API versions](https://app.swaggerhub.com/apis/projectnessie/nessie/0.102.4#/v1) too.

For example, Namespace Creation
CreateNamespace function in catalog/rest.go uses POST method while [nessie v1 api](https://app.swaggerhub.com/apis/projectnessie/nessie/0.102.4#/v1/createNamespace) uses PUT method
API PATH is also different. I have seen similar issues with multiple functions

I am willing to make changes to support Nessie apis, would appreciate some guidance on how to go about it?
1. Should we modify current catalog/rest 
- Use ref and other required params from context.Context for Nessie API.
- Dynamically determine API paths based on whether Nessie or Iceberg REST Catalog is being used.

2. Create a new catalog/nessie to support and maintain nessie specific functionality separately

**Comment by shubham-tomar** [comment]
I have added a [PR](https://github.com/apache/iceberg-go/pull/297) to support Nessie via catalog/rest (namespace related functionalities)

**Comment by zeroshade** [comment]
@shubham-tomar Given that users are using pyiceberg with nessie without needing separate changes to behavior, and iceberg-go is compliant with the REST api (as I based the implementation on pyiceberg), do we actually need changes to the behaviors to support nessie?

**Comment by kevinjqliu** [comment]
Since iceberg-go is a client library for the Apache Iceberg project, I would say adding the custom catalog implementation for Nessie native API's is out of scope. Perhaps the implementation can be adopted by the Nessie project itself

**Comment by shubham-tomar** [comment]
Hi @zeroshade, @kevinjqliu,

I want to use Nessie as a catalog for Iceberg in my data pipeline, which is entirely written in Go. Given the discussion around my PR, I want to clarify the best approach moving forward.

Would it make sense to fork iceberg-go and create a dedicated catalog/nessie package that:
- Implements Nessie-specific API paths and structures while keeping compatibility with Iceberg.
- Use the core functionalities of iceberg-go, ensuring minimal duplication and consistency with the Iceberg ecosystem.

This way, I wouldn’t modify catalog/rest directly but instead build a separate Nessie catalog implementation within my fork. Does this sound like the right approach, or do you have alternative recommendations?

Essentially i wanted to use Nessie for branching logic, and iceberg-go for data CRUD operations

Thanks for your guidance!

**Comment by kevinjqliu** [comment]
Yes you're essentially building a "nessie-go-client" based off of this REST API, which is different from Iceberg's REST API
https://projectnessie.org/develop/rest/

Nessie already has 2 other clients, [python](https://projectnessie.org/develop/python/) and [java](https://projectnessie.org/develop/java/)

**Comment by zeroshade** [comment]
@shubham-tomar you don't need to fork iceberg-go. You simply just need to implement the catalog interface. Once you register the catalog with the registry, you can use it with the rest of the iceberg-go library as-is.

That's why it's separated using the interfaces. You won't need to fork the whole library (and you shouldn't!)

**Comment by shubham-tomar** [comment]
Got it, thank you for your guidance.

**Comment by zeroshade** [comment]
@shubham-tomar If you end up needing help, please reach out because I would really prefer to avoid needing to fork this whole lib :smile:

**Comment by shubham-tomar** [comment]
Hi @zeroshade, i am facing issue while creating table

This is how i am loading catalog
```
config.URI := "http://localhost:19120/iceberg"
config.WarehouseLocation := "s3://warehouse"

iceCatalog, err := catalog.Load(ctx, catalogName, iceberg.Properties{
		"uri":                  config.URI,
		"warehouse":            config.WarehouseLocation,
		"s3.endpoint":          "http://minio:9000", // MinIO endpoint
		"s3.access-key-id":     "admin",             // Default MinIO access key
		"s3.secret-access-key": "password",          // Default MinIO secret key
		"s3.path-style-access": "true",              // Required for MinIO
		"s3.region":            "us-east-1",         // Default region
	})
```
Successfully Loaded catalog:  &{0x14000aef710 0x14000b02270 nessieCatalog map[prefix:main%7Cs3%3A%2F%2Fwarehouse warehouse:s3://warehouse]}
Do endpoint:  http://localhost:19120/iceberg/v1/main%7Cs3%3A%2F%2Fwarehouse/namespaces

i am able to create and List Namespace, 
- [my_namespace_1]


Create Table function
```
func CreateTable(ctx context.Context, iceCatalog *rest.Catalog, ref string, tableIdentifier string, schema *iceberg.Schema, opts ...catalog.CreateTableOpt) error {
	if schema == nil {
		return fmt.Errorf("schema is required to create a table")
	}

	ctx = iceberg.WithRef(ctx, ref)

	identifier := catalog.ToIdentifier(tableIdentifier)

	defaultOpts := []catalog.CreateTableOpt{
		catalog.WithLocation(fmt.Sprintf("s3://warehouse/%s", tableIdentifier)),
		catalog.WithProperties(iceberg.Properties{
			"format-version":       "2",
			"write.format.default": "parquet",
		}),
	}

	table, err := iceCatalog.CreateTable(ctx, identifier, schema, opts...)
	if err != nil {
		return fmt.Errorf("failed to create table: %w", err)
	}
	return nil
}
```

I have add logs in catalog/rest for debugging and getting this

```
DEBUG: Making POST request to: http://localhost:19120/iceberg/v1/main%7Cs3%3A%2F%2Fwarehouse/namespaces/my_namespace_1/tables
DEBUG: Request payload: {"name":"iceberg_table_1","schema":{"type":"struct","fields":[{"type":"int","id":1,"name":"id","required":true,"doc":"unique identifier"},{"type":"string","id":2,"name":"name","required":true,"doc":"user name"},{"type":"timestamp","id":3,"name":"created_at","required":true,"doc":"creation timestamp"}],"schema-id":0,"identifier-field-ids":[]},"location":"s3://warehouse/my_namespace_1.iceberg_table_1","partition-spec":{"spec-id":0,"fields":[]},"write-order":{"order-id":0,"fields":[]},"properties":{"format-version":"2","write.format.default":"parquet"}}
DEBUG: Request headers: map[Content-Type:[application/json]]
DEBUG: Response status: 500 Internal Server Error
DEBUG: Response headers: map[Content-Length:[118] Content-Type:[application/json;charset=UTF-8]]
DEBUG: Response body: {
  "error" : {
    "message" : "HTTP 400 Bad Request",
    "type" : "WebApplicationException",
    "code" : 500
  }
}
DEBUG: Error from POST request: WebApplicationException: HTTP 400 Bad Request
2025/02/15 11:29:16 Failed to create table: failed to create table: WebApplicationException: HTTP 400 Bad Request
```

Looks like some s3 config is missing but i am not able to figure out what exactly is missing, let me know 

My nessie and minio configs

```
nessie:
    image: ghcr.io/projectnessie/nessie:0.102.5-java
    container_name: nessie
    depends_on:
      - minio
    environment:
      - QUARKUS_PROFILE=iceberg
      - NESSIE_ICEBERG_REST_API_ENABLED=true
      - NESSIE_CATALOG_ICEBERG_DEFAULT_WAREHOUSE=s3://warehouse/
      - NESSIE_CATALOG_DEFAULT_WAREHOUSE=warehouse
      - NESSIE_CATALOG_WAREHOUSES_WAREHOUSE_LOCATION=s3://warehouse/
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - NESSIE_OBJECT_STORAGE_ACCESS_KEY=admin
      - NESSIE_OBJECT_STORAGE_SECRET_KEY=password 
      - AWS_ENDPOINT=http://minio:9000
      - NESSIE_OBJECT_STORAGE_AUTH_MODE=STATIC
      # # Default/global S3 configuration settings
      - NESSIE_CATALOG_SERVICE_S3_DEFAULT_OPTIONS_ACCESS_KEY=urn:nessie-secret:quarkus:my-secrets-default
      - MY_SECRETS_DEFAULT_NAME=admin
      - MY_SECRETS_DEFAULT_SECRET=password
    networks:
      iceberg:
    ports:
      - 19120:19120
  # Minio Storage Server
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    networks:
      iceberg:
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
```
