### ISSUE TITLE
Config File Handling

### ISSUE THREAD

**Issue by zeroshade** [apache/iceberg-go#62]
### Feature Request / Improvement

Similar to `pyiceberg`'s [config file](https://py.iceberg.apache.org/configuration/) we should add handling for a config file to make it easier to manipulate the available options for the CLI and library usage.

**Comment by alex-kar** [comment]
@zeroshade What's the initial structure for configuration file would look like?
Something similar to `pyiceberg`'s config:
```
catalog:
  default:
    catalog: rest
    uri: http://localhost:8181/
    output: text
    credential: client-id:client-secret
    warehouse: catalog_name

  custom-catalog:
    catalog: rest
    uri: http://localhost:8181/
    output: text
    credential: client-id:client-secret
    warehouse: catalog_name
```

What about path? `~/iceberg-go.yaml`?

I'd like to work on this, but I need a bit more clarity on the expected config structure.
